gitlab-rails/perforce_swarm/config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'user/recent_projects' => 'application#load_user_projects'
  end

  project_routes = [:configure_helix_mirroring,
                    :enable_helix_mirroring,
                    :disable_helix_mirroring]
  resources :namespaces, path: '/', constraints: { id: /[a-zA-Z.0-9_\-]+/ }, only: [] do
    resources(:projects, constraints: { id: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }, only:
                           project_routes, path: '/') do
      member do
        get :configure_helix_mirroring
        post :enable_helix_mirroring
        post :disable_helix_mirroring
      end
    end
  end

  namespace :perforce_swarm, path: '/gitswarm' do
    resource :git_fusion, only: [], controller: :git_fusion do
      get :new_project
      get :existing_project
      post :reenable_helix_mirroring
      get :reenable_helix_mirroring_status
      get :reenable_helix_mirroring_redirect
    end

    resource :p4_tree, only: [:show], controller: :p4_tree
  end
end

gitlab-rails/perforce_swarm/app/controllers/perforce_swarm/git_fusion_controller.rb
class PerforceSwarm::GitFusionController < ApplicationController
  def existing_project
    init_auto_create

    begin
      # get the desired project and throw if it is already mirrored
      @project = Project.find(params['project_id'])
      fail 'This project is already mirrored in Helix.' if @project.git_fusion_mirrored?
      fail 'This project is already associated to a Helix Git Fusion repository.' if @project.git_fusion_repo.present?

      # first verify we can talk to git-fusion successfully, add error out with details if we cannot
      begin
        PerforceSwarm::GitFusion.run(@fusion_server, 'info')
      rescue => error
        raise 'There was an error communicating with Helix Git Fusion: ' + error.message
      end

      # pre-flight checks against Git Fusion and Perforce
      creator = PerforceSwarm::GitFusion::AutoCreateRepoCreator.new(@fusion_server)
      creator.namespace(@project.namespace.name).project_path(@project.path)
      p4 = PerforceSwarm::P4::Connection.new(creator.config)
      p4.login
      creator.save_preflight(p4)

      @path_template = creator.depot_path + '/...'
    rescue => error
      @errors << error.message
    ensure
      p4.disconnect if p4
    end

    respond_to do |format|
      format.html { render partial: 'existing_project', layout: false }
      format.json { render json: { html: view_to_html_string('perforce_swarm/git_fusion/_existing_project') } }
    end
  end

  def new_project
    init_auto_create

    begin
      @repos = PerforceSwarm::GitFusionRepo.list(@fusion_server, current_user.username)
    rescue => e
      @errors << e.message
    end

    begin
      # attempt to connect to Perforce and ensure the desired project depot exists
      # we do this in its own rescue block so we only grab errors relevant to auto_create
      creator        = PerforceSwarm::GitFusion::AutoCreateRepoCreator.new(@fusion_server)
      p4             = PerforceSwarm::P4::Connection.new(creator.config)
      p4.login
      @project_depot = creator.project_depot
      @depot_exists  = PerforceSwarm::P4::Spec::Depot.exists?(p4, creator.project_depot)
      @path_template = creator.path_template.chomp('/') + '/...'
    rescue => auto_create_error
      @auto_create_errors << auto_create_error.message
    ensure
      p4.disconnect if p4
    end

    respond_to do |format|
      format.html { render partial: 'new_project', layout: false }
      format.json { render json: { html: view_to_html_string('perforce_swarm/git_fusion/_new_project') } }
    end
  end

  def reenable_helix_mirroring_redirect
    init_reenable
    flash[:notice] = 'Helix mirroring successfully re-enabled.' if @project.git_fusion_mirrored?
    redirect_to project_path(@project)
  end

  # gives us the status of the re-enable process for a specific project
  def reenable_helix_mirroring_status
    begin
      init_reenable
      @status = @project.git_fusion_reenable_status
      @error  = @project.git_fusion_reenable_error
    rescue => e
      @status = Project::GIT_FUSION_REENABLE_ERROR
      @error  = e.message
    end

    render json: { status: @status, error: @error }
  end

  # re-enables helix mirroring on the specified project
  def reenable_helix_mirroring
    init_reenable

    # ensure the repo still exists, and the user re-enabling can see it
    error = nil
    begin
      server  = @project.git_fusion_server_id
      repo    = @project.git_fusion_repo_name
      repos   = PerforceSwarm::GitFusionRepo.list(server, current_user.username)
      message = "Either the repo '#{repo}' does not exist, or you do not have permission to access it."
      error   = message unless repos[repo]
    rescue => e
      error = e.message
    end

    if error
      render status: :bad_request, json: { status: 'error', error: error }
      return
    end

    # kick off and background the re-enable process
    job = fork do
      gitlab_shell  = File.expand_path(Gitlab.config.gitlab_shell.path)
      mirror_script = File.join(gitlab_shell, 'perforce_swarm', 'bin', 'gitswarm-mirror')
      args          = [mirror_script, 'reenable_mirroring',
                       @project.git_fusion_repo, @project.path_with_namespace]
      exec Shellwords.shelljoin(args)
    end
    Process.detach(job)
    logger.info("Helix Mirroring re-enable started on project '#{@project.name_with_namespace}' " \
                "by user '#{current_user.username}'")

    # we want to return once the above process has started, so we don't return until
    # either the child process is done, the re-enabling process has started, or
    # we hit a timeout
    begin
      Timeout.timeout(20) do
        sleep(0.1) until reenable_started?(job)
      end
    rescue Timeout::Error
      logger.error('reenable_helix_mirroring failed to start a re-enable shell task.')
    end

    render nothing: true
  end

  protected

  # boolean as to whether we've started the re-enable process - either the project
  # reports re-enabling as being in-progress, or the shell task has quit
  def reenable_started?(shell_pid)
    return true if @project.git_fusion_reenable_status == Project::GIT_FUSION_REENABLE_IN_PROGRESS
    # getpgid returns false if the argument PID doesn't exist (shell task completed or an error)
    return true unless Process.getpgid(shell_pid)
    false
  end

  def init_reenable
    @project = Project.find(params['project_id'])

    # ensure that we have a logged-in user, and that they have permission to re-enable the project
    if !current_user || !current_user.can?(:admin_project, @project)
      fail 'You do not have permissions to re-enable Helix mirroring on this project.'
    end

    # ensure that there is a git fusion repo that we want to re-enable
    fail 'Project is not associated with a Helix Git Fusion repository.' unless @project.git_fusion_repo.present?
  end

  def init_auto_create
    @fusion_server      = params['fusion_server']
    @errors             = []
    @repos              = []
    @project_depot      = ''
    @depot_exists       = false
    @auto_create_errors = []
    @path_template      = ''
  end
end

gitlab-rails/perforce_swarm/app/controllers/projects/application_controller.rb
require Rails.root.join('app', 'controllers', 'projects', 'application_controller')

class Projects::ApplicationController < ApplicationController
  prepend PerforceSwarm::ProjectsControllerHelper
  before_filter :add_project_gon_variables
end

gitlab-rails/perforce_swarm/app/controllers/projects/imports_controller.rb
require Rails.root.join('app', 'controllers', 'projects', 'imports_controller')

module PerforceSwarm
  module ProjectsImportsControllerExtension
    def show
      super unless @project.git_fusion_mirrored? && @project.import_in_progress?
    end
  end
end

class Projects::ImportsController < Projects::ApplicationController
  prepend PerforceSwarm::ProjectsImportsControllerExtension
end

gitlab-rails/perforce_swarm/app/helpers/perforce_swarm/projects_helper.rb
module PerforceSwarm::ProjectsHelper
  def projects_to_simple_json(projects)
    projects.to_json(
      only:    [:id, :name, :path, :visibility_level],
      include: { namespace: { methods: :human_name, only: [:id, :path] } }
    )
  end

  def projects_as_simple_json(projects)
    projects.as_json(
      only:    [:id, :name, :path, :visibility_level],
      include: { namespace: { methods: :human_name, only: [:id, :path] } }
    )
  end
end

gitlab-rails/perforce_swarm/app/helpers/projects_helper.rb
require Rails.root.join('app', 'helpers', 'projects_helper')

module ProjectsHelper
  # Don't linkify the last section of the title, so there is a larger click
  # area for the dropdown. Plus the link would just take you to your current page.
  def project_title(project, name = nil, _url = nil)
    namespace_link =
      if project.group
        link_to(simple_sanitize(project.group.name), group_path(project.group))
      else
        owner = project.namespace.owner
        link_to(simple_sanitize(owner.name), user_path(owner))
      end

    project_link = simple_sanitize(project.name)
    project_link = link_to(project_link, project_path(project)) if name

    full_title  = namespace_link + ' / ' + project_link
    full_title += ' &middot; '.html_safe + simple_sanitize(name) if name

    content_tag :span do
      full_title
    end
  end

  def helix_missing_config_error(project)
    gitlab_shell_config.git_fusion.entry(project.git_fusion_server_id)
    return nil
  rescue
    tooltip = <<-EOM
      Configuration for the Helix Git Fusion server '#{ERB::Util.html_escape(project.git_fusion_server_id)}'
      is either missing, or is not properly configured in GitSwarm.
    EOM
    return tooltip.html_safe
  end

  def mirroring_errors(project, user)
    # user does not have adequate permissions to enable mirroring
    tooltip = <<-EOM
      GitSwarm is configured for Helix mirroring, but you lack permissions to manage it for this project.<br />
      To manage Helix mirroring, you must be a project 'master', 'owner' or a site admin.
    EOM
    return tooltip.html_safe unless mirroring_permitted?(project, user)

    # Git Fusion integration is explicitly disabled
    tooltip = <<-EOM
      GitSwarm's Helix Git Fusion integration is disabled.<br />
      To manage Helix mirroring, please have an admin enable the Git Fusion integration.
    EOM
    return tooltip.html_safe unless git_fusion_enabled?

    # no Git Fusion entries found in the config
    tooltip = <<-EOM
      GitSwarm's Helix Git Fusion integration is enabled, however no Git Fusion instances have been configured.<br />
      To manage Helix mirroring, please have an admin configure at least one Git Fusion instance.
    EOM
    return tooltip.html_safe unless git_fusion_instances?

    # include details if there is a configuration error with one or more Git Fusion servers
    tooltip = <<-EOM
      GitSwarm's Helix Git Fusion integration is enabled, however there is a configuration error:<br />
      #{ERB::Util.html_escape(git_fusion_server_error)}
    EOM
    return tooltip.html_safe if git_fusion_server_error

    # project is a candidate for disabling mirroring, but the config ID no longer exists
    tooltip = helix_missing_config_error(project)
    return tooltip.html_safe if project.git_fusion_mirrored? && tooltip

    # this project is already mirrored or is a candidate for re-enabling
    return '' if project.git_fusion_repo.present?

    # no Git Fusion config entries have auto create enabled, or it is mis-configured
    tooltip = <<-EOM
      None of the Helix Git Fusion instances GitSwarm knows about are configured for 'auto create'.<br />
      To enable Helix mirroring, please have an admin configure at least one Git Fusion instance for auto create.
    EOM
    return tooltip.html_safe unless mirroring_configured?

    nil
  end

  def mirroring_tooltip(project, user, for_button = false)
    errors = mirroring_errors(project, user)
    return errors if errors && !errors.empty?

    # no tooltip if project is already mirrored
    return '' if project.git_fusion_mirrored?

    verb = project.git_fusion_repo.present? ? 're-enable' : 'get'
    # all good in the 'hood - tooltip is slightly different for the button vs the text below the clone URL
    return "Click to #{verb} mirroring!" if for_button
    "Click \"Helix Mirroring\" below to #{verb} mirroring!"
  end

  def helix_reenable_mirroring_tooltip(project)
    tooltip = helix_missing_config_error(project)
    return tooltip.html_safe if mirroring_configured? && tooltip

    begin
      url     = git_fusion_url!(project)
      tooltip = 'This project has no record of being previously mirrored.'
      return tooltip.html_safe unless url && !url.empty?
    rescue => e
      return ERB::Util.html_escape(e.message).html_safe
    end

    nil
  end

  # time (as a string) of the last successful fetch from Git Fusion, or false if no timestamp is present
  def git_fusion_last_fetched(project)
    PerforceSwarm::Mirror.last_fetched(project.repository.path_to_repo).strftime('%F %T %z')
  rescue
    return false
  end

  # the error being reported by Git Fusion mirroring, or false if there are no errors
  def git_fusion_last_fetch_error(project)
    PerforceSwarm::Mirror.last_fetch_error(project.repository.path_to_repo)
  end

  # returns the rendered URL for a currently or previously mirrored project
  def git_fusion_url!(project)
    if project.git_fusion_mirrored?
      return PerforceSwarm::Repo.new(project.repository.path_to_repo).mirror_url_object.clear_for_user.to_s
    elsif project.git_fusion_repo.present?
      return PerforceSwarm::GitFusionRepo.resolve_url(project.git_fusion_repo).to_s
    else
      return ''
    end
  end

  # returns the rendered URL for a currently or previously mirrored project, returning false
  # if there was an exception thrown (e.g. URL is invalid or contains a server ID that no
  # longer exists)
  def git_fusion_url(project)
    git_fusion_url!(project)
  rescue
    return false
  end

  # boolean as to whether there are configured Git Fusion instances in the config
  def git_fusion_instances?
    !git_fusion_servers.empty?
  rescue
    false
  end

  # boolean as to whether the current user is permitted to enable mirroring on the given project
  def mirroring_permitted?(project, user)
    user && user.can?(:admin_project, project)
  end

  # returns true if there is at least one configured Git Fusion repository that supports convention-based mirroring
  # note that we are doing pre-flight style checks with the config only, and not actually connecting to Helix at this
  # point
  def mirroring_configured?
    return false unless git_fusion_instances?

    # ensure that at least one entry is configured for convention-based mirroring
    gitlab_shell_config.git_fusion.entries.each do |_id, entry|
      return true if entry.auto_create_configured?
    end
    # we didn't find one, or there are no entries at all
    false
  rescue
    # if we encountered an exception with the above, mirroring is definitely not possible
    return false
  end

  def git_fusion_enabled?
    gitlab_shell_config.git_fusion.enabled?
  rescue
    # as the code sits, this is not likely to occur, but we're being defensive anyway
    return false
  end

  def git_fusion_server_error
    return nil unless git_fusion_enabled?

    # Call the url method on each server to validate the config
    gitlab_shell_config.git_fusion.entries.each { |_id, config| config.url }
    nil
  rescue => e
    return e.message
  end

  def git_fusion_servers(default_first_auto_create: false)
    return [] unless git_fusion_enabled?

    options  = []
    servers  = gitlab_shell_config.git_fusion.entries
    selected = params['git_fusion_entry']
    servers.each do |id, config|
      options.push(["#{id} (#{config[:url]})", id])
      # skip setting our selected element if we've already got one, or
      # if the current config entry isn't configured for auto-create, and
      # we're looking for the first one that is
      next if selected || (default_first_auto_create && !config.auto_create_configured?)
      selected = id
    end
    servers.empty? ? [] : options_for_select(options, selected)
  end

  def git_fusion_repos(repos)
    options = [['<Select repository to enable>', '']]
    repos.each do |name, _description|
      options.push([name, name])
    end
    repos.empty? ? [] : options_for_select(options)
  end

  # note we can't call this gitlab_config as there is already a helper for gitlab-ce's config with that name
  def gitlab_shell_config
    @gitlab_shell_config ||= PerforceSwarm::GitlabConfig.new
  end

  def helix_mirroring_button(project, user, color = 'white')
    # wrapper for tooltip
    haml_tag(:span,
             data:  { title: mirroring_tooltip(project, user, true), html: 'true' },
             class: 'has_tooltip mirror-button-wrapper') do
      # parameters for an enable button
      can_mirror = mirroring_permitted?(@project, current_user) && mirroring_configured?
      attributes = { class: 'btn btn-save helix-mirroring' + (can_mirror ? '' : ' disabled') }

      # add the button at the appropriate haml indent level
      haml_concat(
        link_to(configure_helix_mirroring_namespace_project_path(project.namespace, project), attributes) do
          haml_concat(icon('helix-icon ' + color))
          haml_concat('Helix Mirroring')
        end
      )
    end
  end
end

gitlab-rails/perforce_swarm/app/views/perforce_swarm/git_fusion/projects/_configure_helix_mirroring.html.haml
= render partial: 'perforce_swarm/git_fusion/projects/mirroring_config_errors'
- error = git_fusion_server_error || mirroring_errors(@project, current_user)
- if !error || error.empty?
  .git-fusion-mirroring
  - servers = git_fusion_servers(default_first_auto_create: true)
  - if servers.empty?
    .description.slead
      This Helix GitSwarm instance is not pointing to any Helix Git Fusion servers. In order to enable mirroring, have an admin
      = link_to 'see these directions.', help_page_path('workflow', 'helix_mirroring', 'configuration'), target: '_blank'
  - else
    %h3
      Select a Helix server to mirror the project to
    .control-group.form-inline
      .control-label.mirroring-server-select
        Helix Git Fusion Server:
        = select_tag(:git_fusion_entry, servers, class: 'form-control')
      .git-fusion-mirroring-data
    :javascript
      var mirror_config = new GitFusionMirror("#{@project.id}");

gitlab-rails/perforce_swarm/app/views/perforce_swarm/git_fusion/projects/_currently_mirrored_settings.html.haml
%p
- can_disable      = mirroring_permitted?(@project, current_user) && mirroring_configured?
- button_class     = 'btn btn-save' + (can_disable ? '' : ' disabled')
- git_fusion_url   = git_fusion_url(@project)
This project is currently mirrored to the
= "'#{@project.git_fusion_server_id}'"
Helix Git Fusion server on the repo
= "'#{@project.git_fusion_repo_name}'"
%p
- if git_fusion_url && git_fusion_url.is_a?(String) && !git_fusion_url.empty?
  %p
    Git Fusion URL:
    = git_fusion_url(@project)
    %br
    %em Note: This is the URL on which Git Fusion is hosting this repository. If you wish to clone the GitSwarm project, you should use the URL specified on the
    = link_to('project details page.', project_path(@project))
- if git_fusion_last_fetched(@project)
  %p
    This project was last updated from Helix Git Fusion
    %time.time_ago.js-timeago{ datetime: git_fusion_last_fetched(@project), data: {placement: 'top', toggle: 'tooltip'} }
      = git_fusion_last_fetched(@project)
  - if git_fusion_last_fetch_error(@project)
    %p
      During the last fetch, the following error occurred:
      %pre
        = git_fusion_last_fetch_error(@project)
- else
  %p
    It appears this project hasn't updated from Helix Git Fusion yet.
= render partial: 'perforce_swarm/git_fusion/projects/mirroring_config_errors'
%span.mirror-button-wrapper
  = link_to disable_helix_mirroring_namespace_project_path(@project.namespace, @project), { method: 'post', class: button_class, data: { confirm: 'Are you sure you want to disable Helix Mirroring?' } } do
    = icon 'helix-icon white'
    Disable Helix Mirroring

gitlab-rails/perforce_swarm/app/views/perforce_swarm/git_fusion/projects/_mirroring_config_errors.html.haml
- error = git_fusion_server_error || mirroring_errors(@project, current_user)
- if error && !error.empty?
  .helix-error
    %h4 Configuration Error:
    %p.fixed-width
      = error
  %p
    For help on configuring your Helix Git Fusion instances, have an admin
    = link_to 'see these directions.', help_page_path('workflow', 'helix_mirroring', 'configuration'), target: '_blank'

gitlab-rails/perforce_swarm/app/views/perforce_swarm/git_fusion/projects/_previously_mirrored_settings.html.haml
- git_fusion_url   = git_fusion_url(@project)
- has_fusion_url   = git_fusion_url && !git_fusion_url.empty?
- can_reenable     = mirroring_permitted?(@project, current_user) && mirroring_configured? && has_fusion_url
- button_class     = 'btn btn-save helix-mirroring' + (can_reenable ? '' : ' disabled')
- reenable_tooltip = helix_reenable_mirroring_tooltip(@project)
- error            = git_fusion_server_error || mirroring_errors(@project, current_user)
- error            = nil unless error && !error.empty?
%p
  Mirroring for this project has been disabled.
%p
  This project was previously mirroring the
  = "'#{@project.git_fusion_server_id}'"
  Helix Git Fusion server on the repo
  = "'#{@project.git_fusion_repo_name}'"
%p
  - if can_reenable
    Git Fusion URL:
    = git_fusion_url
    %br
    %em Note: This is the URL on which Git Fusion is hosting this repository. If you wish to clone the GitSwarm project, you should use the URL specified on the
    = link_to('project details page.', project_path(@project))
  - else
    - if error
      = render partial: 'perforce_swarm/git_fusion/projects/mirroring_config_errors'
    - else
      .helix-error
        %h4 Error:
        %p.fixed-width
          = reenable_tooltip
        %p
          = link_to help_page_path('workflow', 'helix_mirroring', 'configuration') do
            %strong= 'Please fix the configuration'
          to re-enable mirroring for this project.

.reenable-mirror-wrapper
  = link_to '#', class: button_class do
    = icon 'helix-icon white'
    Re-enable Helix Mirroring
  .reenable-status
- reenable_error = @project.git_fusion_reenable_error
- params = { reenable_url: reenable_helix_mirroring_perforce_swarm_git_fusion_path(project_id: @project.id) }
- params[:reenable_status_url] = reenable_helix_mirroring_status_perforce_swarm_git_fusion_path(project_id: @project.id)
- params[:status] = @project.git_fusion_reenable_status
- params[:error]  = reenable_error.is_a?(String) ? reenable_error.strip : reenable_error
- params[:success_redirect] = reenable_helix_mirroring_redirect_perforce_swarm_git_fusion_path(project_id: @project.id)
:javascript
  var reenable_helix_mirroring = new ReenableHelixMirroring(#{params.to_json});

gitlab-rails/perforce_swarm/app/views/perforce_swarm/git_fusion/projects/helix_mirroring.html.haml
- page_title   'Helix Mirroring'
- header_title 'Helix Mirroring'

.git-fusion-mirroring
  %h2
    Helix Mirroring
  .description.slead
  - if @project.git_fusion_mirrored?
    -# currently mirrored, so show relevant mirroring settings and the disable button
    = render partial: 'perforce_swarm/git_fusion/projects/currently_mirrored_settings'
  - elsif @project.git_fusion_repo.present?
    -# project is not currently mirrored, but a repo is specified; it is a candidate for re-enabling mirroring
    = render partial: 'perforce_swarm/git_fusion/projects/previously_mirrored_settings'
  - else
    -# project isn't currently mirrored, so show the configure mirroring form
    = render partial: 'perforce_swarm/git_fusion/projects/configure_helix_mirroring'
:javascript
  $('.js-timeago').timeago()